runtime: go116
env: standard
instance_class: B2
handlers:
  - url: .*
    script: auto
basic_scaling:
  max_instances: 1
network: {}
service_account: gosia-michal-zaproszenia@appspot.gserviceaccount.com