runtime: go116
env: standard
instance_class: B2
handlers:
  - url: /img
    static_dir: static/img
  - url: /js
    static_dir: static/js
  - url: /css
    static_dir: static/css
  - url: /mp3
    static_dir: static/mp3
  - url: /.*
    redirect_http_response_code: 301
    script: auto
basic_scaling:
  max_instances: 1
  idle_timeout: 60s
network: {}
service_account: gosia-michal-zaproszenia@appspot.gserviceaccount.com
env_variables:
  GCLOUD_DATASET_ID: gosia-michal-zaproszenia
app_engine_apis: true